# Generated by Django 6.0.4 on 2026-04-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artwork_category_alter_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
