# Generated by Django 6.0.4 on 2026-04-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(default='General 1', max_length=50),
        ),
    ]
