# Generated by Django 6.0.4 on 2026-04-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_artwork_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('art_type', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='references/')),
            ],
        ),
    ]
