# Generated by Django 6.0.4 on 2026-04-17 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commission',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commission',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='commissions/'),
        ),
    ]
